<a href="https://colab.research.google.com/github/nattapongbam/229352-StatisticalLearning681/blob/main/Copy_of_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [2]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [55]:
a = torch.tensor([1.])
a

tensor([1.])

### Convert a tensor to scalar

In [53]:
b = a[0].item()
b

1.0

### Creating 2D tensor

In [56]:
c = torch.tensor([[1., 2.], [3., 4.]])
c

tensor([[1., 2.],
        [3., 4.]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [57]:
d = c.numpy()
d

array([[1., 2.],
       [3., 4.]], dtype=float32)

### Convert from numpy array to tensor

In [58]:
f = torch.from_numpy(d)
f

tensor([[1., 2.],
        [3., 4.]])

## PyTorch and GPU

check if GPU is available

In [59]:
torch.cuda.is_available()

True

In [100]:
c = c.cuda()
c

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [102]:
e = c.cpu().numpy()
e

array([[1., 2.],
       [3., 4.]], dtype=float32)

## Basic operations

In [66]:
c * 2

tensor([[2., 4.],
        [6., 8.]])

In [67]:
c - 1

tensor([[0., 1.],
        [2., 3.]])

### Matrix multiplication

In [71]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [72]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [73]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [74]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [3]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [46]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [6]:
R1 = torch.rand(2, 3)
R1

tensor([[0.2939, 0.9558, 0.8495],
        [0.3676, 0.0840, 0.6289]])

In [10]:
R2 = torch.randn(2, 3)
R2

tensor([[ 0.3655,  0.0039,  0.0822],
        [ 0.8159, -0.0033, -0.3589]])

In [44]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

In [14]:
R1.shape

torch.Size([2, 3])

### Checking the shape of a tensor

In [15]:
u = torch.arange(6)
u.shape

torch.Size([6])

### Changing the shape of a tensor

In [19]:
v = u.reshape(2, 3)
v.shape

torch.Size([2, 3])

In [20]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [25]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [26]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [27]:
# concatenate
e = torch.cat([a, b], axis=0)
e # มิติเท่าเดิม

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [29]:
display(a,b)

tensor([0, 1, 2, 3])

tensor([1, 2, 3, 4])

In [28]:
f = torch.cat([a.reshape(2, 2), b.reshape(2, 2)], axis=0)
f

tensor([[0, 1],
        [2, 3],
        [1, 2],
        [3, 4]])

### Squeezing a tensor (removing an extra dimension)

In [31]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )


## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

In [93]:
torch.inverse(torch.tensor([[1., 2.], [3., 4.]]))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
# X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
# print(X)

# X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
# print(X)

In [106]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

In [107]:
one = torch.ones(200, 1)

In [108]:
X

tensor([[ 1.7017,  1.8814, -2.2282,  ...,  1.2352,  0.0247,  0.0911],
        [-0.1980,  0.2510, -1.3084,  ...,  0.7970,  0.0662, -0.8002],
        [ 0.7745,  0.9387,  0.4498,  ...,  0.0834, -0.8303,  2.2198],
        ...,
        [ 0.3705, -0.1042,  0.3133,  ..., -1.2909, -1.2308, -0.5224],
        [-1.0014,  0.3083, -0.0410,  ..., -0.8305, -0.6998,  0.5144],
        [-0.5031,  1.4989, -0.7130,  ..., -0.0339,  0.0478,  0.6068]])

In [109]:
X = torch.cat([one, X], axis=1)
X

tensor([[ 1.0000,  1.7017,  1.8814,  ...,  1.2352,  0.0247,  0.0911],
        [ 1.0000, -0.1980,  0.2510,  ...,  0.7970,  0.0662, -0.8002],
        [ 1.0000,  0.7745,  0.9387,  ...,  0.0834, -0.8303,  2.2198],
        ...,
        [ 1.0000,  0.3705, -0.1042,  ..., -1.2909, -1.2308, -0.5224],
        [ 1.0000, -1.0014,  0.3083,  ..., -0.8305, -0.6998,  0.5144],
        [ 1.0000, -0.5031,  1.4989,  ..., -0.0339,  0.0478,  0.6068]])

In [ ]:
y = X @ b + e
y

In [111]:
b_hat = torch.inverse(X.t() @ X) @ X.t() @ y
b_hat

tensor([[-0.3184],
        [-1.1671],
        [ 0.0386],
        [-0.1986],
        [-0.3073],
        [-1.0052],
        [-0.0847],
        [ 2.3196]])

In [ ]:
y_hat = X @ b_hat
y_hat

In [113]:
y = y.numpy()
y_hat = y_hat.numpy()

In [114]:
MSE = (1/200) * (np.sum((y - y_hat)**2))
MSE

np.float32(1.004545)